package tui

// model_settings_dotted.go — the dotted-key registry for the Settings screen.
// Split out of model_settings_scope.go, which is at the 600-line cap: this is a
// standalone lookup table with its own drift test, not scope logic.

// settingDottedKeys maps every settings row key to its config-field-registry
// dotted key. It is a superset of settingTOMLPaths: the global-only rows (theme,
// logging, cache, lsp_query, session, semantics) that LoadProject does not
// override per-project still need a registry identity for help text and reload
// tier. The per-language [lsp.<lang>] rows are resolved by dottedKeyFor, not
// here. TestSettingsRegistryDrift keeps this in step with settingTOMLPaths.
var settingDottedKeys = map[settingKey]string{
	skTheme:                         "ui.theme",
	skPathStyle:                     "ui.path_style",
	skWebPort:                       "web.port",
	skLogLevel:                      "log_level",
	skLogFormat:                     "log_format",
	skLogFile:                       "log_file",
	skStrict:                        "edits.strict",
	skShowWriteDiff:                 "edits.show_write_diff",
	skRelayWriteDiff:                "edits.relay_write_diff",
	skBlockDirtyWrites:              "edits.block_dirty_writes",
	skFsync:                         "edits.fsync",
	skRateLimit:                     "edits.rate_limit_per_minute",
	skPostWriteDiagMs:               "edits.post_write_diagnostics_ms",
	skPostWriteCrossFile:            "edits.post_write_cross_file",
	skPostWriteCrossFileSettleMs:    "edits.post_write_cross_file_settle_ms",
	skConcurrentSkewMs:              "edits.concurrent_write_skew_ms",
	skRefuseHomeRoots:               "walk.refuse_home_roots",
	skTopology:                      "topology.enabled",
	skTopoResyncOnAttach:            "topology.resync_on_attach",
	skTopoWatch:                     "topology.watch",
	skTopoMaxFileSize:               "topology.max_file_size_bytes",
	skTopoExtractTimeoutSec:         "topology.extract_timeout_seconds",
	skTopoResyncBatch:               "topology.resync_batch",
	skTopoResyncPauseMs:             "topology.resync_pause_ms",
	skTopoResyncIntervalMin:         "topology.resync_interval_minutes",
	skExcludePatterns:               "topology.exclude_patterns",
	skQuality:                       "quality.enabled",
	skQualityMode:                   "quality.mode",
	skQualityTimeoutMs:              "quality.timeout_ms",
	skQualityMaxFindings:            "quality.max_findings_per_file",
	skAnalysers:                     "quality.analysers",
	skGitWrites:                     "git.allow_writes",
	skGitDestructive:                "git.allow_destructive",
	skGitPush:                       "git.allow_push",
	skGitCommitTrailer:              "git.commit_trailer",
	skProtectedBranches:             "git.protected_branches",
	skGitWriteTimeout:               "git.write_timeout",
	skGitDetachAfter:                "git.detach_after",
	skIdleThresholdMin:              "session.idle_threshold_minutes",
	skEvictionTTLMin:                "session.eviction_ttl_minutes",
	skPersistState:                  "session.persist_state",
	skPersistStateTTLMin:            "session.persist_state_ttl_minutes",
	skMemoryEnabled:                 "memory.enabled",
	skMemoryGeneratedSummaries:      "memory.generated_summaries",
	skMemoryInjectHints:             "memory.inject_hints",
	skMemoryHintBudgetBytes:         "memory.hint_budget_bytes",
	skMemoryEpisodicBudgetBytes:     "memory.episodic_budget_bytes",
	skMemoryMaxHints:                "memory.max_hints",
	skMemoryIdleSummaryMin:          "memory.idle_summary_minutes",
	skMemoryGeneratedKeep:           "memory.generated_memory_keep",
	skContextHints:                  "context.hints",
	skCollabPeerAwareness:           "collab.peer_awareness",
	skCollabHintBudgetBytes:         "collab.hint_budget_bytes",
	skCollabIntents:                 "collab.intents",
	skCollabMailbox:                 "collab.mailbox",
	skCollabCrossProject:            "collab.cross_project",
	skCollabAllowUnidentifiedWrites: "collab.allow_unidentified_writes",
	skCollabMaxExchanges:            "collab.max_exchanges",
	skCollabChatBudgetBytes:         "collab.chat_budget_bytes",
	skCollabMaxWaitSec:              "collab.max_wait_seconds",
	skCollabWakeWindowSec:           "collab.wake_window_seconds",
	skCollabWakePeerWindowSec:       "collab.wake_peer_window_seconds",
	skCollabKnowledgeHandoff:        "collab.knowledge_handoff",
	skCollabIntentTTLMin:            "collab.intent_ttl_minutes",
	skCollabNoteTTLMin:              "collab.note_ttl_minutes",
	skCollabKeepDelivered:           "collab.keep_delivered_notes",
	skRastroEnabled:                 "rastro.enabled",
	skRastroPath:                    "rastro.path",
	skXcodeAutoBuildServer:          "xcode.auto_build_server",
	skXcodeScheme:                   "xcode.scheme",
	skXcodeTimeout:                  "xcode.timeout",
	skAutoAttach:                    "workspace.auto_attach",
	skAutoAttachPersist:             "workspace.auto_attach_persist",
	skAllowDependencyReads:          "workspace.allow_dependency_reads",
	skDiscoverSiblings:              "workspace.discover_siblings",
	skChildScanDepth:                "workspace.child_scan_depth",
	skExtraRoots:                    "workspace.extra_roots",
	skReadRoots:                     "workspace.read_roots",
	skCacheTTL:                      "cache.ttl",
	skCacheMaxSize:                  "cache.max_size",
	skLSPTimeout:                    "lsp_query.timeout",
	skSemEnabled:                    "semantics.enabled",
	skSemProvider:                   "semantics.provider",
	skSemModel:                      "semantics.model",
	skSemBaseURL:                    "semantics.base_url",
	skSemAPIKeyEnv:                  "semantics.api_key_env",
	skSemAPIKey:                     "semantics.api_key",
	skSemRerankCandidates:           "semantics.rerank_candidates",
	skSemTimeout:                    "semantics.timeout",
	skAgentConfigWrites:             "agent_config_writes",
}
